In [1]:
%pip install -q datasets pandas

In [2]:
from datasets import load_dataset
import pandas as pd

dataset = load_dataset(
    "fancyzhx/amazon_polarity",
    split="train[:10]"
)

df = pd.DataFrame(dataset)
df = df.rename(columns={
    "content": "text",
    "label": "original_label"
})

df["original_label"] = df["original_label"].map({
    0: "negative",
    1: "positive"
})

df.insert(0, "review_id", range(1, len(df) + 1))

print("Număr de recenzii:", len(df))
display(df[["review_id", "text", "original_label"]])

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

README.md:   0%|          | 0.00/6.81k [00:00<?, ?B/s]

amazon_polarity/train-00000-of-00004.par(…): reconstructing file:   0%|          |  0.00B /  260MB

amazon_polarity/train-00000-of-00004.par(…): downloading bytes:           |  0.00B

amazon_polarity/train-00001-of-00004.par(…): reconstructing file:   0%|          |  0.00B /  258MB

amazon_polarity/train-00001-of-00004.par(…): downloading bytes:           |  0.00B

amazon_polarity/train-00002-of-00004.par(…): reconstructing file:   0%|          |  0.00B /  255MB

amazon_polarity/train-00002-of-00004.par(…): downloading bytes:           |  0.00B

amazon_polarity/train-00003-of-00004.par(…): reconstructing file:   0%|          |  0.00B /  254MB

amazon_polarity/train-00003-of-00004.par(…): downloading bytes:           |  0.00B

amazon_polarity/test-00000-of-00001.parq(…): reconstructing file:   0%|          |  0.00B /  117MB

amazon_polarity/test-00000-of-00001.parq(…): downloading bytes:           |  0.00B

Generating train split:   0%|          | 0/3600000 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/400000 [00:00<?, ? examples/s]

Număr de recenzii: 10

   review_id                                               text original_label
0          1  This sound track was beautiful! It paints the ...       positive
1          2  I'm reading a lot of reviews saying that this ...       positive
2          3  This soundtrack is my favorite music of all ti...       positive
3          4  I truly like this soundtrack and I enjoy video...       positive
4          5  If you've played the game, you know how divine...       positive
5          6  I am quite sure any of you actually taking the...       positive
6          7  This is a self-published book, and if you want...       negative
7          8  I loved Whisper of the wicked saints. The stor...       positive
8          9  I just finished reading Whisper of the Wicked ...       positive
9         10  This was a easy to read book that made me want...       positive

In [3]:
%pip install -q -U google-genai

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires google-auth==2.49.0, but you have google-auth 2.62.0 which is incompatible.

In [4]:
from google import genai
print("Instalarea google-genai a reușit!")

Instalarea google-genai a reușit!

In [5]:
from google import genai
from google.colab import userdata

api_key = userdata.get("GEMINI_API_KEY")
client = genai.Client(api_key=api_key)

response = client.models.generate_content(
    model="gemini-2.5-flash",
    contents="Classify the sentiment of this review: 'This product is excellent!' Reply with one word: positive or negative."
)

print(response.text)

ClientError: 401 UNAUTHENTICATED. {'error': {'code': 401, 'message': 'API key not valid. Please pass a valid API key.', 'status': 'UNAUTHENTICATED', 'details': [{'@type': 'type.googleapis.com/google.rpc.ErrorInfo', 'reason': 'ACCESS_TOKEN_TYPE_UNSUPPORTED', 'metadata': {'method': 'google.ai.generativelanguage.v1beta.GenerativeService.GenerateContent', 'service': 'generativelanguage.googleapis.com'}}]}}

In [6]:
from google.colab import userdata

api_key = userdata.get("GEMINI_API_KEY")

print("Cheie configurată:", bool(api_key))
print("Prefixul cheii:", api_key[:3] if api_key else "Lipsă")
print("Lungimea cheii:", len(api_key) if api_key else 0)

Cheie configurată: True
Prefixul cheii: AQ.
Lungimea cheii: 53

In [8]:

import requests
from google.colab import userdata

api_key = userdata.get("GEMINI_API_KEY")

url = "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent"

response = requests.post(
    url,
    headers={
        "x-goog-api-key": api_key,
        "Content-Type": "application/json"
    },
    json={
        "contents": [
            {
                "parts": [
                    {"text": "Reply with one word: OK"}
                ]
            }
        ]
    },
    timeout=30
)

print("Status HTTP:", response.status_code)
print("Răspuns:", response.text[:1500])

Status HTTP: 404
Răspuns: {
  "error": {
    "code": 404,
    "message": "This model models/gemini-2.5-flash is no longer available to new users. Please update your code to use models/gemini-3.8-flash for the latest features and improvements. We recommend you to use the Interactions API (https://ai.google.dev/gemini-api/docs/get-started).",
    "status": "NOT_FOUND"
  }
}

In [9]:

import requests
from google.colab import userdata

api_key = userdata.get("GEMINI_API_KEY")

url = "https://generativelanguage.googleapis.com/v1beta/models/gemini-3.8-flash:generateContent"

response = requests.post(
    url,
    headers={
        "x-goog-api-key": api_key,
        "Content-Type": "application/json"
    },
    json={
        "contents": [
            {
                "parts": [
                    {
                        "text": "Classify the sentiment of this review: 'This product is excellent!' Reply with one word: positive or negative."
                    }
                ]
            }
        ]
    },
    timeout=30
)

print("Status HTTP:", response.status_code)
print("Răspuns:", response.text[:1500])

ReadTimeout: HTTPSConnectionPool(host='generativelanguage.googleapis.com', port=443): Read timed out. (read timeout=30)

In [10]:

import requests
from google.colab import userdata

api_key = userdata.get("GEMINI_API_KEY")

url = "https://generativelanguage.googleapis.com/v1beta/models/gemini-3.8-flash:generateContent"

try:
    response = requests.post(
        url,
        headers={
            "x-goog-api-key": api_key,
            "Content-Type": "application/json"
        },
        json={
            "contents": [
                {
                    "parts": [
                        {"text": "Reply with one word: OK"}
                    ]
                }
            ],
            "generationConfig": {
                "maxOutputTokens": 10
            }
        },
        timeout=90
    )

    print("Status HTTP:", response.status_code)
    print("Răspuns:", response.text[:1500])

except requests.exceptions.Timeout:
    print("Cererea a expirat după 90 de secunde.")
except requests.exceptions.RequestException as e:
    print("Eroare de conexiune:", str(e))

Cererea a expirat după 90 de secunde.

In [11]:

import requests
from google.colab import userdata

api_key = userdata.get("GEMINI_API_KEY")

url = "https://generativelanguage.googleapis.com/v1beta/interactions"

try:
    response = requests.post(
        url,
        headers={
            "x-goog-api-key": api_key,
            "Content-Type": "application/json"
        },
        json={
            "model": "gemini-3.8-flash",
            "input": "Classify this review sentiment: 'This product is excellent!' Reply with one word: positive or negative.",
            "store": False
        },
        timeout=60
    )

    print("Status HTTP:", response.status_code)
    print("Răspuns:", response.text[:2000])

except requests.exceptions.Timeout:
    print("Cererea a expirat. Trecem la alternativa fără API.")
except requests.exceptions.RequestException as e:
    print("Eroare de conexiune:", str(e))

Status HTTP: 503
Răspuns: {"error":{"message":"gemini-3.8-flash is currently experiencing high demand, spikes in demand are usually temporary. Please try again later.","code":"service_unavailable"}}

In [12]:

%pip install -q transformers torch

In [13]:

from transformers import pipeline

sentiment_model = pipeline(
    "sentiment-analysis",
    model="distilbert/distilbert-base-uncased-finetuned-sst-2-english"
)

results = sentiment_model(
    df["text"].fillna("").astype(str).tolist(),
    truncation=True,
    max_length=512
)

df["model_sentiment"] = [
    "positive" if result["label"] == "POSITIVE" else "negative"
    for result in results
]

df["confidence"] = [
    round(result["score"], 4) for result in results
]

display(
    df[["review_id", "text", "original_label",
        "model_sentiment", "confidence"]]
)

config.json:   0%|          | 0.00/629 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B /  268MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/104 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

,review_id,text,original_label,model_sentiment,confidence
0,1,This sound track was beautiful! It paints the ...,positive,positive,0.9992
1,2,I'm reading a lot of reviews saying that this ...,positive,positive,0.9938
2,3,This soundtrack is my favorite music of all ti...,positive,positive,0.9998
3,4,I truly like this soundtrack and I enjoy video...,positive,positive,0.9998
4,5,"If you've played the game, you know how divine...",positive,positive,0.9998
5,6,I am quite sure any of you actually taking the...,positive,positive,0.9999
6,7,"This is a self-published book, and if you want...",negative,negative,0.9998
7,8,I loved Whisper of the wicked saints. The stor...,positive,positive,0.9998
8,9,I just finished reading Whisper of the Wicked ...,positive,positive,0.9990
9,10,This was a easy to read book that made me want...,positive,positive,0.9996

In [14]:

%pip install -q datasets pandas pyarrow

In [15]:

from datasets import load_dataset
import pandas as pd

# Încărcăm datele din Amazon Polarity
dataset = load_dataset(
    "fancyzhx/amazon_polarity",
    split="train"
)

# Selectăm aleatoriu 5.300 de recenzii
sample = dataset.shuffle(seed=42).select(range(5300))

df_all = pd.DataFrame(sample)
df_all = df_all.rename(
    columns={
        "content": "text",
        "label": "original_label"
    }
)

# Păstrăm etichetele originale separat
df_all["original_label"] = df_all["original_label"].map(
    {0: "negative", 1: "positive"}
)

# ID unic pentru fiecare recenzie
df_all.insert(0, "review_id", range(1, len(df_all) + 1))

# Eliminăm eventualele texte lipsă
df_all = df_all.dropna(subset=["text"]).reset_index(drop=True)

print("Număr de recenzii:", len(df_all))
display(df_all.head())

Număr de recenzii: 5300

,review_id,original_label,title,text
0,1,negative,Anyone who likes this better than the Pekinpah...,All the pretty people in this film. Even the R...
1,2,negative,Author seems mentally unstable,I know that Tom Robbins has a loyal following ...
2,3,positive,Spaetzle Noodles,This type of spaetzle maker is easier to manuv...
3,4,positive,Cool product until the cats lost it . . . .,My cats seemed to be amused to work for their ...
4,5,positive,Works as expected,I've had no problems running this with my Dell...

In [17]:

# Primele 300 de recenzii vor fi etichetate manual
manual_df = df_all.iloc[:300][
    ["review_id", "text", "original_label"]
].copy()

manual_df["manual_label"] = ""

# Restul de 5.000 vor fi etichetate ulterior prin LLM
llm_df = df_all.iloc[300:][
    ["review_id", "text", "original_label"]
].copy()

print("Set pentru etichetare manuală:", len(manual_df))
print("Set pentru etichetare LLM:", len(llm_df))

print("\nExemplu din setul manual:")
display(manual_df.head())

print("\nExemplu din setul LLM:")
display(llm_df.head())

Set pentru etichetare manuală: 300
Set pentru etichetare LLM: 5000

Exemplu din setul manual:

,review_id,text,original_label,manual_label
0,1,All the pretty people in this film. Even the R...,negative,
1,2,I know that Tom Robbins has a loyal following ...,negative,
2,3,This type of spaetzle maker is easier to manuv...,positive,
3,4,My cats seemed to be amused to work for their ...,positive,
4,5,I've had no problems running this with my Dell...,positive,

Exemplu din setul LLM:

,review_id,text,original_label
300,301,"Interesting to look at, but not the least do a...",negative
301,302,The first generation of Sennheiser Wireless he...,negative
302,303,This is a fine film and Sandra Bullock shows w...,positive
303,304,I saw this book in the store and decided to se...,negative
304,305,State of Fear by Michael Crichton is a good re...,negative

In [19]:

# Salvăm setul complet
df_all.to_parquet(
    "amazon_reviews_sample.parquet",
    index=False
)

# Salvăm setul pentru LLM
llm_df.to_parquet(
    "amazon_reviews_llm.parquet",
    index=False
)

# CSV pentru etichetarea manuală
manual_df.to_csv(
    "amazon_reviews_manual.csv",
    index=False,
    encoding="utf-8-sig"
)

print("Fișierele au fost salvate.")

Fișierele au fost salvate.

In [20]:

from google.colab import files

files.download("amazon_reviews_manual.csv")